###
GET http://localhost:5170/weatherforecast HTTP/1.1

###
POST http://localhost:5170/graphql HTTP/1.1
Content-Type: application/json

{
  "query": "{\r\n  book {\r\n    title\r\n    author {\r\n      name\r\n    }\r\n  }\r\n}\n"
}